# Generated by Django 2.1.11 on 2020-03-28 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_selected_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('semester', models.CharField(max_length=3)),
                ('domain', models.CharField(choices=[('WEBSITE', 'WEBSITE'), ('SOCIAL_MEDIA', 'SOCIAL_MEDIA')], max_length=100)),
                ('is_consenting', models.BooleanField()),
                ('created_at', models.DateField()),
                ('last_updated', models.DateField()),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='selected_theme',
            field=models.CharField(choices=[('dark', 'dark'), ('light', 'light')], default='light', max_length=50, verbose_name='selected theme'),
        ),
        migrations.AddField(
            model_name='photoconsent',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photoconsent_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photoconsent',
            name='updated_by',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photoconsent_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photoconsent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_consents', to=settings.AUTH_USER_MODEL),
        ),
    ]
