# Generated by Django 2.1.11 on 2020-03-31 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200328_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoconsent',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='photoconsent',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='selected_theme',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=50, verbose_name='selected theme'),
        ),
    ]
